In [2]:
a = 12

In [3]:
print(a)

12


In [4]:
print(type(a))

<class 'int'>


In [6]:
b=0.1

In [7]:
print(type(b))

<class 'float'>


type() gives data type
shift+enter to execute

In [8]:
id(a)

140731210328856

In [9]:
# comment starts with hash symbol 

In [16]:
mentor_name = "monal"

In [18]:
print("mentor_name")

mentor_name


In [19]:
#booleans or bool

In [ ]:
#Type casting is to convert int to float

In [21]:
a=1

In [22]:
float(a)

1.0

In [1]:
print("hello")

hello


In [2]:
import time

In [1]:
!pip install numpy

'pip' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
import sys
print(sys.executable)

c:\Users\SKANDA\Documents\Data-Science-Krish\level_1\level-1-env\Scripts\python.exe


In [3]:
%pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 8.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.3 MB 8.9 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.3 MB 8.9 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.3 MB 8.2 MB/s eta 0:00:01
   -------------------- ------------------- 6.3/12.3 MB 7.0 MB/s eta 0:00:01
   ---------------------- ----------------- 6.8/12.3 MB 6.1 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.3 MB 5.5 MB/s eta 0:00:01
   ------------------------- -------------- 7.9/12.3 MB 5.0 MB/s eta 0:00:01
   --------------------------- ------------ 8.4/12.3 MB 4.8 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.3 MB 4.5 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.3 MB 4.4 MB/s eta 0:00:01
   --------------------------------- ------ 10.2/12.3 MB 4.2 MB/s eta 0:00:01
   --


[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
print(np.__version__)

2.4.2


In [1]:
def add(a, b):   # a and b are parameters
    return a + b

add(2, 3)        # 2 and 3 are arguments

5

In [2]:
arr_1 = np.array([1,2])
print(arr_1)
print(type(arr_1))

[1 2]
<class 'numpy.ndarray'>


In [11]:
npz_3 = np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [18]:
np.empty((2,3), dtype=np.int16)

array([[     0,      0,      0],
       [     0, -22224,  13663]], dtype=int16)

In [10]:
npz_3.ndim


4

In [36]:
npn = np.random.rand(3,6,5)
print(npn)

[[[0.5595623  0.24142594 0.37084729 0.30280857 0.50294511]
  [0.13620847 0.76625078 0.7960172  0.44009654 0.99088164]
  [0.54836448 0.07374997 0.24223905 0.96901014 0.27813332]
  [0.9560255  0.33870031 0.95424891 0.78052537 0.71452053]
  [0.67154042 0.76524137 0.20201084 0.51029532 0.08533265]
  [0.3566497  0.3380433  0.00166201 0.01002187 0.14190998]]

 [[0.638526   0.37780382 0.82919021 0.01591722 0.04446309]
  [0.73714195 0.92440503 0.93570209 0.11450625 0.37004837]
  [0.20126175 0.50473602 0.01834372 0.41449345 0.97840887]
  [0.32624724 0.8838534  0.74392763 0.15480822 0.33218611]
  [0.71456178 0.40667736 0.45858911 0.93321797 0.29200036]
  [0.43831923 0.82589863 0.91373901 0.54403893 0.71439758]]

 [[0.6863291  0.14111771 0.38865217 0.91950495 0.1700577 ]
  [0.95332649 0.22758344 0.02337033 0.21391385 0.28841725]
  [0.77249571 0.78851401 0.48542464 0.40474424 0.46503804]
  [0.03295664 0.66113156 0.604534   0.84323259 0.96071683]
  [0.71904798 0.75372322 0.57033343 0.83823932 0.119

In [26]:
npn.ndim

1

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
npz_1 = np.full((3, 3), 5)
print(npz_1)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [1]:
npz_1 = np.full((3, 3), 5))

SyntaxError: unmatched ')' (3989019143.py, line 1)

In [2]:
words = {"ai", "ml", "ai"}
print(words)

{'ai', 'ml'}


In [1]:
print("test")

test
